In [1]:
from platform import python_version
print(f'Versão da Linguagem Python Usada Neste Jupyter Notebook: {python_version()}')

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.13.4


# Numpy

[https://numpy.org/](https://numpy.org/)

In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.0'

In [4]:
# Instrução para instalar uma versão exata do pacote em Python
# !pip install 2.3.0

In [5]:
arrl = np.array([ 10,21,32,43,48,15,76,57,89])

In [6]:
print(arrl)

[10 21 32 43 48 15 76 57 89]


In [7]:
display(arrl)

array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [8]:
type(arrl)

numpy.ndarray

In [9]:
arrl.shape

(9,)

In [10]:
print(arrl)

[10 21 32 43 48 15 76 57 89]


In [11]:
# Imprimindo um elemento específico no array
print(arrl[4])

48


In [12]:
# Indexação
print(arrl[1:4])

[21 32 43]


In [13]:
# Indexação
print(arrl[1:4+1])

[21 32 43 48]


In [14]:
# Criando  listas de índices
indices = [1,2,5,6]

In [15]:
arrl[indices]

array([21, 32, 15, 76])

In [16]:
# Cria uma máscara booleana para os elementos pares
mask = (arrl % 2 == 0)

In [17]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [18]:
arrl[mask]

array([10, 32, 48, 76])

In [19]:
# Alterando um elemento do array
arrl[0] = 100

In [20]:
print(arrl)

[100  21  32  43  48  15  76  57  89]


In [21]:
#Não é possível incluir elemento de outro tipo
try:
    arrl[0] = 'Novo elemento'

except:
    print(f'Operação não permitida!')

Operação não permitida!


In [22]:
arr2 = np.array(list(range(1,6)))

In [23]:
print(arr2)

[1 2 3 4 5]


In [24]:
type(arr2)

numpy.ndarray

In [25]:
arr2

array([1, 2, 3, 4, 5])

In [26]:
# Usando métodos do array NumPy
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [27]:
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [28]:
np

<module 'numpy' from 'c:\\Users\\Robert Fernandes\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\numpy\\__init__.py'>

In [29]:
# A função arange cria um array NumPy contendo uma progressão aritmética a partir de um intervalo — start, stop, Step
arr3 = np.arange(0,50,5)

In [30]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [31]:
type(arr3)

numpy.ndarray

In [32]:
np.shape(arr3)

(10,)

In [33]:
print(arr3.dtype)

int64


In [34]:
# Cria um array preenchido com zeros
arr4 = np.zeros(10)

In [35]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
# Retorna 1 nas posições em diagonal e 0 no restante
arr5 = np.eye(5)

In [37]:
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [38]:
# Os valores passados como parâmetro, formam uma diagonal
arr6 = np.diag(np.array(range(1,5)))

In [39]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [40]:
# Array de valores booleanos
arr7 = np.array([True,False,False,True])

In [41]:
print(arr7)

[ True False False  True]


In [42]:
# Array de strings
arr8 = np.array(['Linguagem Python','Linguagem R','Linguagem Julia'])

In [43]:
print(arr8)

['Linguagem Python' 'Linguagem R' 'Linguagem Julia']


In [44]:
print(np.linspace(0,10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [45]:
print(np.linspace(0,10,15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [46]:
print(np.logspace(0,5,10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


In [49]:
lista = [[13,81,22],[0,34,59],[21,48,94]]

In [50]:
arr11 = np.matrix(lista)

In [51]:
type(arr11)

numpy.matrix

In [52]:

print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]
